import Project.Phase2.Constrains
import Project.Phase2.NearLitterAction
import Project.Phase2.CompleteOrbit
import Project.Phase2.FlexibleCompletion
import Project.Phase2.StructAction
import Project.Phase2.Sublitter
import Project.Phase2.NearLitterCompletion
import Project.Phase2.Approximation
import Project.Phase2.Basic
import Project.Phase2.AtomCompletion
import Project.Phase2.Flexible
import Project.Phase2.Reduction
import Project.Phase2.FillAtomRange
import Project.Phase2.CompleteAction
import Project.Phase2.LitterCompletion
import Project.Phase2.FillAtomOrbits
import Project.Phase2.Refine
import Project.Phase1.CodeEquiv
import Project.Phase1.Allowable
import Project.Phase1.AMap
import Project.Phase1.Basic
import Project.Phase1.Code
import Project.Phase1.Tangle
import Project.Phase1.FMap
import Project.Mathlib.Order
import Project.Mathlib.Transfer
import Project.Mathlib.Group
import Project.Mathlib.GroupAction
import Project.Mathlib.WithBot
import Project.Mathlib.Prod
import Project.Mathlib.Nat
import Project.Mathlib.Pointwise
import Project.Mathlib.Cardinal
import Project.Mathlib.Logic
import Project.Mathlib.Ordinal
import Project.Mathlib.Equiv
import Project.Mathlib.Logic.Equiv.LocalPerm
import Project.Phase0.Support
import Project.Phase0.Pretangle
import Project.Phase0.Index
import Project.Phase0.StructPerm
import Project.Phase0.Litter
import Project.Phase0.Params

#align_import all

